import test from "node:test";
import assert from "node:assert/strict";
import { AUDIENCES, DURATION, RECIPES, applyDirection, calculateRhythmScore, createDefaultShow, createSequence, deleteEvent, duplicateEvent, evaluateAudience, formatTime, generateShow, parseShow, seededRandom, updateEvent } from "../src/model.js";

test("default show is a valid 60-second composition", () => {
  const show=createDefaultShow();assert.equal(show.events.length,25);assert.ok(show.events.every(e=>e.time>=0&&e.time<DURATION));assert.deepEqual([...show.events].sort((a,b)=>a.time-b.time),show.events);
});
test("seeded random is deterministic",()=>{const a=seededRandom(42),b=seededRandom(42);assert.deepEqual(Array.from({length:8},a),Array.from({length:8},b));});
test("event edits are immutable",()=>{const show=createDefaultShow(),id=show.events[0].id;const changed=updateEvent(show,id,{intensity:.2});assert.notEqual(show,changed);assert.notEqual(show.events[0],changed.events[0]);assert.equal(show.events[0].intensity,.7);assert.equal(changed.events[0].intensity,.2);});
test("duplicate and delete preserve source composition",()=>{const show=createDefaultShow(),id=show.events[0].id;const copied=duplicateEvent(show,id);assert.equal(copied.events.length,26);assert.equal(show.events.length,25);assert.equal(deleteEvent(copied,id).events.length,25);});
test("time formatting clamps and pads",()=>{assert.equal(formatTime(0),"00:00.0");assert.equal(formatTime(5.27),"00:05.2");assert.equal(formatTime(60),"01:00.0");assert.equal(formatTime(-2),"00:00.0");});
test("rhythm score rewards an authored arc without rewarding raw quantity",()=>{const score=calculateRhythmScore(createDefaultShow());assert.ok(score.total>=60&&score.total<=100);assert.ok(score.arc>50);assert.deepEqual(calculateRhythmScore({events:[]}),{total:20,timing:20,variety:0,arc:0,breathing:0});});
test("procedural shows are deterministic and preserve a pause before the finale",()=>{const first=generateShow({seed:123}),second=generateShow({seed:123});assert.deepEqual(first,second);assert.ok(first.events.length>15);assert.equal(first.events.filter(event=>event.time>38&&event.time<44).length,0);});
test("import validates and clamps untrusted performance data",()=>{const parsed=parseShow({name:"Test",palette:"gold",seed:2,events:[{type:"ring",time:90,x:4,y:-2,intensity:9}]});assert.equal(parsed.events[0].time,59.9);assert.equal(parsed.events[0].x,.95);assert.equal(parsed.events[0].y,.1);assert.equal(parsed.events[0].intensity,1);assert.throws(()=>parseShow({palette:"missing",events:[]}));});
test("creative direction translates safe language into reversible show edits",()=>{const original=createDefaultShow();const result=applyDirection(original,"Abertura minimalista, pausa, névoa e finale gigantesco cyberpunk");assert.equal(result.show.palette,"cyber");assert.equal(result.show.atmosphere,"mist");assert.ok(result.show.events.filter(event=>event.time<18).length<original.events.filter(event=>event.time<18).length);assert.equal(result.show.events.filter(event=>event.time>38&&event.time<45).length,0);assert.ok(result.show.events.filter(event=>event.time>=56).length>=3);assert.equal(original.atmosphere,"clear");});
test("effect library exposes ten distinct safe visual archetypes",()=>{assert.equal(Object.keys(RECIPES).length,10);assert.ok(Object.values(RECIPES).every(recipe=>recipe.particles>0&&recipe.life>0));});
test("sequence tool creates a spatial and temporal crescendo",()=>{const original=createDefaultShow(),sequenced=createSequence(original,{start:10,type:"spiral",count:7,spacing:.5,direction:"right"});const additions=sequenced.events.filter(event=>event.id.startsWith("sequence-"));assert.equal(additions.length,7);assert.equal(additions[0].time,10);assert.equal(additions.at(-1).time,13);assert.ok(additions.at(-1).intensity>additions[0].intensity);assert.ok(additions.at(-1).x>additions[0].x);assert.equal(original.events.length,25);});
test("audience simulation evaluates composition instead of raw event count",()=>{const show=createDefaultShow(),evaluation=evaluateAudience(show);assert.ok(evaluation.overall>=0&&evaluation.overall<=100);assert.ok(evaluation.highlights.length>0);assert.equal(evaluation.audienceName,AUDIENCES.cinematic.name);const noisy={...show,events:Array.from({length:200},(_,index)=>({...show.events[0],id:`noise-${index}`,time:index%60}))};assert.ok(evaluateAudience(noisy).restraint<evaluation.restraint);});
test("show parser preserves supported audience and rain atmosphere",()=>{const show=createDefaultShow();const parsed=parseShow({...show,audience:"festival",atmosphere:"rain"});assert.equal(parsed.audience,"festival");assert.equal(parsed.atmosphere,"rain");});
